name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First step name
        run: echo "Hello World"
      - name: Second Step
        run: echo "Done"
